"use client";
import { useState } from "react";

const whatsappNumber="5531995732862";
const whatsappMessages:Record<string,string>={
  "hero-whatsapp":"Olá, Thiago! Conheci a Regis Investing e quero evoluir no Day Trade. Gostaria de entender qual programa faz mais sentido para o meu momento.",
  "trader-estruturado":"Olá, Thiago! Tenho interesse no programa Trader Estruturado. Gostaria de saber como funciona, quais conteúdos são abordados e para quem ele é indicado.",
  "mentoria-performance":"Olá, Thiago! Tenho interesse na Mentoria Performance. Gostaria de entender como funciona o acompanhamento individual e se ele é adequado ao meu momento como trader.",
  "faq-whatsapp":"Olá, Thiago! Visitei a página da Regis Investing e fiquei com uma dúvida sobre os programas. Pode me ajudar?"
};

const icons:Record<string,React.ReactNode>={chart:<><path d="M4 4v16h16"/><path d="m7 15 4-4 3 2 6-7"/><path d="M16 6h4v4"/></>,target:<><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3"/></>,shield:<><path d="M12 3 4.5 6v5.5c0 4.7 3.2 7.8 7.5 9.5 4.3-1.7 7.5-4.8 7.5-9.5V6L12 3Z"/><path d="m9 12 2 2 4-5"/></>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5M7 10h6M10 7v6"/></>,list:<><path d="M9 6h11M9 12h11M9 18h11M4 6l1 1 2-2M4 12l1 1 2-2M4 18l1 1 2-2"/></>};
const audience=[["chart","Está começando no Day Trade e quer aprender da forma correta;"],["target","Já opera, mas ainda não consegue manter consistência;"],["shield","Deseja ser aprovado em uma Mesa Proprietária;"],["search","Busca aprimorar sua leitura de mercado e sua gestão de risco;"],["list","Quer evoluir de forma estruturada e profissional."]];
const entryItems=["Construção de um plano operacional","Fundamentos da leitura de mercado","Gestão de risco aplicada ao Day Trade","Estratégias práticas e objetivas","Critérios de entrada e saída","Organização e análise das operações","Desenvolvimento de disciplina e consistência","Psicologia e mentalidade aplicadas ao trading"];
const performanceItems=["Todo o conteúdo do Trader Estruturado","Diagnóstico individual do perfil operacional","Plano de evolução personalizado","Estratégias avançadas de mercado","Preparação para Mesas Proprietárias","Análise detalhada das operações","Correção de erros de execução","Aprimoramento da gestão de risco","Acompanhamento estratégico individual","Feedback direcionado"];
const faqs=[["Preciso ter experiência para começar?","Não. O programa Trader Estruturado foi desenvolvido para quem está começando e também para quem já opera, mas precisa organizar sua leitura, seu plano operacional e sua gestão de risco."],["Qual é a diferença entre o Trader Estruturado e a Mentoria Performance?","O Trader Estruturado é o programa de entrada, voltado para a construção de uma base operacional sólida. A Mentoria Performance oferece acompanhamento individual e mais avançado, com diagnóstico, análise de operações, correção de execução e planejamento personalizado."],["A mentoria garante resultados ou aprovação em Mesa Proprietária?","Não. O desempenho depende de dedicação, disciplina, gestão de risco, aplicação do método e condições de mercado. A mentoria oferece conhecimento, orientação e acompanhamento, mas não promete lucros nem aprovação garantida."],["Como saber qual programa é mais adequado para mim?","Para construir ou reorganizar sua base, o programa Trader Estruturado pode ser o caminho mais adequado. Para quem busca análise individual e acompanhamento estratégico, a Mentoria Performance é a opção mais personalizada."],["Como faço para receber mais informações?","Clique no botão de contato e fale diretamente pelo WhatsApp. Você poderá explicar seu momento atual e receber mais informações sobre a modalidade mais adequada aos seus objetivos."]];

function Icon({name}:{name:string}){return <svg viewBox="0 0 24 24" aria-hidden="true">{icons[name]}</svg>}
function Label({children}:{children:React.ReactNode}){return <p className="section-label">{children}</p>}
function CTA({children,tag}:{children:React.ReactNode;tag:string}){const message=whatsappMessages[tag];const whatsappUrl=`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;return <a className="cta" href={whatsappUrl} target="_blank" rel="noopener noreferrer" data-cta={tag} aria-label="Falar com Thiago Regis no WhatsApp"><span>{children}</span><b aria-hidden="true">↗</b></a>}

export default function Home(){const[openFaq,setOpenFaq]=useState(0);const[menuOpen,setMenuOpen]=useState(false);return <main>
  <header className="header"><a className="brand" href="#inicio"><img className="brand-logo" src="/logo-regis.png" alt="" width="42" height="42"/>REGIS <span>INVESTING</span></a><button className="menu-button" aria-label="Abrir menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}><i/><i/><i/></button><nav className={menuOpen?"nav open":"nav"} aria-label="Navegação principal">{[["#para-quem","Para quem é a mentoria"],["#quem-sou-eu","Quem sou eu"],["#faq","FAQ"],["#contato","Contato"]].map(([href,label])=><a key={href} href={href} onClick={()=>setMenuOpen(false)}>{label}</a>)}</nav></header>
  <section className="hero" id="inicio"><div className="market-lines"/><div className="hero-copy"><h1>O mercado financeiro não transforma vidas <em>por acaso.</em></h1><p>Ele recompensa quem está disposto a <strong>estudar, evoluir e executar com disciplina.</strong></p><CTA tag="hero-whatsapp">QUERO EVOLUIR NO DAY TRADE</CTA></div><div className="hero-photo"><img src="/assets/hero-thiago.png" alt="Thiago Regis" width="760" height="900" fetchPriority="high"/></div></section>
  <section className="section audience" id="para-quem"><Label>PARA QUEM É A MENTORIA?</Label><h2>Se você:</h2><div className="audience-grid">{audience.map(([icon,text],i)=><article className={i===4?"audience-item last":"audience-item"} key={text}><span className="icon"><Icon name={icon}/></span><p>{text}</p></article>)}</div><div className="callout">Se você quer <strong>levar o Day Trade a sério</strong>, essa mentoria foi desenvolvida para você.</div></section>
  <section className="section learning" id="aprendizado"><div className="section-heading"><Label>O QUE VOCÊ IRÁ APRENDER</Label><h2>Escolha o caminho ideal para a sua evolução</h2><p>Duas modalidades desenvolvidas para diferentes momentos da sua jornada no Day Trade.</p></div><div className="product-grid"><article className="product-card"><span className="pill">PROGRAMA DE ENTRADA</span><h3>Trader Estruturado</h3><p>Construa uma base operacional sólida para tomar decisões com mais clareza, controle e disciplina no mercado.</p><ul>{entryItems.map(x=><li key={x}>{x}</li>)}</ul><CTA tag="trader-estruturado">QUERO CONHECER O PROGRAMA</CTA></article><article className="product-card featured"><div className="pill-row"><span className="pill">ACOMPANHAMENTO INDIVIDUAL</span><span className="pill solid">MAIS PERSONALIZADO</span></div><h3>Mentoria Performance</h3><p>Um acompanhamento individual e estratégico para traders que desejam corrigir falhas, aprimorar a execução e acelerar sua evolução.</p><ul>{performanceItems.map(x=><li key={x}>{x}</li>)}</ul><CTA tag="mentoria-performance">QUERO UM ACOMPANHAMENTO INDIVIDUAL</CTA><small>Vagas limitadas para preservar a qualidade do acompanhamento.</small></article></div></section>
  <section className="section about" id="quem-sou-eu"><div className="about-photo"><img src="/assets/thiago-sobre.png" alt="Thiago Regis, fundador da Regis Investing" width="760" height="1000" loading="lazy"/></div><div className="about-copy"><Label>QUEM SOU EU</Label><h2>Thiago Regis</h2><p className="subtitle">Fundador da Regis Investing</p><p>Thiago Regis acredita que o sucesso no mercado não depende de promessas milagrosas, mas de um processo consistente baseado em conhecimento, técnica e gestão de risco.</p><p>Sua trajetória é semelhante à de milhões de brasileiros: alguém que decidiu mudar de realidade por meio do trabalho, da dedicação e da busca constante por evolução.</p><div className="timeline"><div><b>2021</b><p>Iniciou sua jornada no mercado financeiro investindo em ações. O interesse rapidamente se transformou em uma paixão pelo mercado.</p></div><div><b>2022</b><p>Mergulhou no universo do Day Trade. Entre acertos, erros e aprendizados, consolidou a convicção que hoje compartilha com seus alunos.</p></div></div><blockquote>Grandes resultados exigem <strong>disciplina, método e consistência.</strong> Não existe atalho para quem deseja viver do mercado.</blockquote><p>Hoje, além de operar profissionalmente, Thiago direciona seu trabalho para operações em Mesas Proprietárias, auxiliando traders a desenvolverem uma mentalidade profissional, aperfeiçoarem sua execução e conquistarem consistência operacional.</p><p>Como fundador da Regis Investing, sua missão é formar traders preparados para enfrentar o mercado com estratégia, controle emocional e gerenciamento de risco.</p></div></section>
  <section className="section faq" id="faq"><div className="section-heading"><Label>TIRE SUAS DÚVIDAS</Label><h2>Perguntas frequentes</h2><p>Encontre respostas rápidas sobre os programas da Regis Investing.</p></div><div className="accordion">{faqs.map(([q,a],i)=><article className={openFaq===i?"faq-item open":"faq-item"} key={q}><button aria-expanded={openFaq===i} aria-controls={`faq-${i}`} onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{q}</span><b>{openFaq===i?"−":"+"}</b></button><div className="faq-panel" id={`faq-${i}`}><p>{a}</p></div></article>)}</div></section>
  <section className="contact" id="contato"><p>Ainda ficou com alguma dúvida?</p><h2>Vamos conversar sobre o seu momento no Day Trade.</h2><CTA tag="faq-whatsapp">FALAR COM THIAGO REGIS NO WHATSAPP</CTA></section>
  <footer><a className="brand" href="#inicio"><img className="brand-logo" src="/logo-regis.png" alt="" width="42" height="42"/>REGIS <span>INVESTING</span></a><p>Os conteúdos e mentorias possuem finalidade exclusivamente educacional e não constituem recomendação individual de investimento. Operações no mercado financeiro envolvem riscos e podem resultar em perdas. Não há promessa de rentabilidade, aprovação em Mesa Proprietária ou garantia de resultados.</p><small>© 2026 Regis Investing. Todos os direitos reservados.</small></footer>
</main>}
